export const urls = [
    {url: 'https://sliding.toys/mystic-square/8-puzzle/daily/', title: "8 puzzle"},
    {url: 'https://longdogechallenge.com/', title: "Long Doge Challenge"},
    {url: 'https://maze.toys/mazes/mini/daily/', title: "Daily Mini Maze"},
    {url: 'https://optical.toys', title: "Optical Toys"},
    {url: 'https://paint.toys/calligram/', title: "Calligram"},
    {url: 'https://puginarug.com', title: "Pug in a Rug"},
    {url: 'https://memory.toys/classic/easy/', title: "Classic Memory Game"},
    {url: 'https://alwaysjudgeabookbyitscover.com', title: "Always Judge a Book by Its Cover"},
    {url: 'https://clicking.toys/flip-grid/neat-nine/3-holes/', title: "Flip Grid"},
    {url: 'https://weirdorconfusing.com/', title: "Weird or Confusing"},
    {url: 'https://checkbox.toys/scale/', title: "Checkbox Scale"},
    {url: 'https://binarypiano.com/', title: "Binary Piano"},
    {url: 'https://mondrianandme.com/', title: "Mondrian and Me"},
    {url: 'https://onesquareminesweeper.com/', title: "One Square Minesweeper"},
    {url: 'https://cursoreffects.com', title: "Cursor Effects"},
    {url: 'http://floatingqrcode.com/', title: "Floating QR Code"},
    {url: 'https://thatsthefinger.com/', title: "That's the Finger"},
    {url: 'http://heeeeeeeey.com/', title: "Heeeeeeeey"},
    {url: 'http://corndog.io/', title: "Corndog"},
    {url: 'http://eelslap.com/', title: "Eel Slap"},
    {url: 'http://www.staggeringbeauty.com/', title: "Staggering Beauty"},
    {url: 'https://smashthewalls.com/', title: "Smash the Walls"},
    {url: 'https://jacksonpollock.org/', title: "Jackson Pollock"},
    {url: 'http://endless.horse/', title: "Endless Horse"},
    {url: 'http://drawing.garden/', title: "Drawing Garden"},
    {url: 'https://www.trypap.com/', title: "Try PAP"},
    {url: 'http://www.republiquedesmangues.fr/', title: "République des Mangues"},
    {url: 'https://paint.toys/', title: "Paint Toys"},
    {url: 'https://checkboxrace.com/', title: "Checkbox Race"},
    {url: 'http://www.rrrgggbbb.com/', title: "RRRGGGBBB"},
    {url: 'http://www.koalastothemax.com/', title: "Koalas to the Max"},
    {url: 'https://rotatingsandwiches.com/', title: "Rotating Sandwiches"},
    {url: 'http://randomcolour.com/', title: "Random Colour"},
    {url: 'http://maninthedark.com/', title: "Man in the Dark"},
    {url: 'http://cat-bounce.com/', title: "Cat Bounce"},
    {url: 'https://thezen.zone/', title: "The Zen Zone"},
    {url: 'http://ihasabucket.com/', title: "I Has a Bucket"},
    {url: 'https://toms.toys', title: "Tom's Toys"},
    {url: 'http://www.hackertyper.com/', title: "Hacker Typer"},
    {url: 'https://pointerpointer.com', title: "Pointer Pointer"},
    {url: 'http://www.partridgegetslucky.com/', title: "Partridge Gets Lucky"},
    {url: 'http://www.ismycomputeron.com/', title: "Is My Computer On"},
    {url: 'http://www.nullingthevoid.com/', title: "Nulling the Void"},
    {url: 'http://www.muchbetterthanthis.com/', title: "Much Better Than This"},
    {url: 'http://www.yesnoif.com/', title: "Yes No If"},
    {url: 'http://www.wutdafuk.com/', title: "Wut Da Fuk"},
    {url: 'http://unicodesnowmanforyou.com/', title: "Unicode Snowman For You"},
    {url: 'https://memory.toys', title: "Memory Toys"},
    {url: 'https://zoomquilt.org/', title: "Zoom Quilt"},
    {url: 'https://dadlaughbutton.com/', title: "Dad Laugh Button"},
    {url: 'http://papertoilet.com/', title: "Paper Toilet"},
    {url: 'https://loopedforinfinity.com/', title: "Looped for Infinity"},
    {url: 'https://www.ripefordebate.com/', title: "Ripe for Debate"},
    {url: 'https://end.city/', title: "End City"},
    {url: 'https://elonjump.com/', title: "Elon Jump"},
    {url: 'https://www.bouncingdvdlogo.com/', title: "Bouncing DVD Logo"},
    {url: 'https://sometimes.red/sometimes.blue/', title: "Sometimes Red Sometimes Blue"},
    {url: 'https://potatoortomato.com/', title: "Potato or Tomato"},
    {url: 'https://iamawesome.com/', title: "I Am Awesome"},
    {url: 'https://pleaselike.com/', title: "Please Like"},
    {url: 'https://corgiorgy.com/', title: "Corgi Orgy"},
    {url: 'https://pixelsfighting.com/', title: "Pixels Fighting"},
    {url: 'http://www.omfgdogs.com/', title: "OMG Dogs"},
    {url: 'https://existentialcrisis.com/', title: "Existential Crisis"},
    {url: 'http://donothingfor2minutes.com/', title: "Do Nothing for 2 Minutes"},
    {url: 'https://buzzybuzz.biz/', title: "Buzzy Buzz"},
    {url: 'https://whatsmystarbucksname.com/', title: "What's My Starbucks Name"},
    {url: 'http://www.everydayim.com/', title: "Every Day I'm"},
    {url: 'https://boringboringboring.com/', title: "Boring Boring Boring"},
    {url: 'https://imaninja.com/', title: "I'm a Ninja"},
    {url: 'https://thepigeon.org/', title: "The Pigeon"},
    {url: 'http://isitwhite.com/', title: "Is It White"},
    {url: 'http://iamthewalrus.com/', title: "I Am the Walrus"},
    {url: 'https://www.myinstants.com/', title: "My Instants"},
    {url: 'https://neal.fun/deep-sea/', title: "Deep Sea"},
    {url: 'https://neal.fun/spend/', title: "Spend"},
    {url: 'https://neal.fun/password-game/', title: "Password Game"},
    {url: 'https://neal.fun/absurd-trolley-problems/', title: "Absurd Trolley Problems"},
    {url: 'https://neal.fun/ambient-chaos/', title: "Ambient Chaos"},
    {url: 'https://stars.chromeexperiments.com/', title: "100,000 Stars"},
    {url: 'http://orteil.dashnet.org/cookieclicker/', title: "Cookie Clicker"},
    {url: 'https://www.geoguessr.com/', title: "GeoGuessr"},
    {url: 'https://www.futureme.org/', title: "FutureMe"},
    {url: 'https://stellarium-web.org/', title: "Stellarium Web"},
    {url: 'https://quickdraw.withgoogle.com/', title: "Quick, Draw!"},
    {url: 'https://www.incredibox.com/', title: "Incredibox"},
    {url: 'https://earth.google.com/web/', title: "Google Earth"},
    {url: 'http://weavesilk.com/', title: "Weave Silk"},
    {url: 'https://29a.ch/sandbox/2011/havana/', title: "Havana"},
    {url: 'https://inspirobot.me/', title: "Inspirobot"},
    {url: 'https://thispersondoesnotexist.com/', title: "This Person Does Not Exist"},
    {url: 'https://thiscatdoesnotexist.com/', title: "This Cat Does Not Exist"},
    {url: 'https://theuselessweb.com/', title: "The Useless Web"},
    {url: 'https://isitnormal.com/', title: "Is It Normal"},
    {url: 'https://www.mapcrunch.com/', title: "MapCrunch"},
    {url: 'https://www.mentalfloss.com/amazingfacts/', title: "Mental Floss"},
    {url: 'https://www.shutupandtakemymoney.com/', title: "Shut Up and Take My Money"},
    {url: 'https://www.boredbutton.com/', title: "Bored Button"},
    {url: 'https://whatdoestheinternetthink.net/', title: "What Does the Internet Think"},
    {url: 'https://randomstreetview.com/', title: "Random Street View"},
    {url: 'https://www.pun.me/pages/random-pun.php', title: "Random Pun"},
    {url: 'https://www.google.com/teapot', title: "I'm a teapot"},
    {url: 'http://intotime.com/', title: "Into Time"},
    {url: 'http://www.everynoise.com/engenremap.html', title: "Every Noise at Once"},
    {url: 'https://www.flightradar24.com/', title: "Flightradar24"},
    {url: 'https://earth.nullschool.net/', title: "Earth Nullschool"},
    {url: 'https://www.windows93.net/', title: "Windows 93"},
    {url: 'https://html9responsivezerogrid.com/', title: "HTML9 Responsive Boilerstrap JS"},
    {url: 'https://www.pointercrate.com/demonlist/', title: "Pointercrate Demonlist"},
    {url: 'http://www.trashloop.com/', title: "Trashloop"},
    {url: 'https://www.hanzismatter.com/', title: "Hanzi Matter"},
    {url: 'http://www.null.net/', title: "Nullnet"},
    {url: 'https://www.isitdownrightnow.com/', title: "Is It Down Right Now"},
    {url: 'https://www.howmanyofme.com/', title: "How Many of Me"},
    {url: 'https://www.randy.club/', title: "Randy Club"},
    {url: 'https://pool.toys/', title: "Pool Toys"},
    {url: 'https://draw.toys/flip-grid/neat-nine/3-holes/', title: "Draw Toys"},
    {url: 'https://thisissand.com/', title: "This Is Sand"},
    {url: 'https://www.myfonts.com/WhatTheFont/', title: "WhatTheFont"},
    {url: 'https://www.remove.bg/', title: "Remove Background"},
    {url: 'https://waifu2x.udp.jp/', title: "Waifu2x"},
    {url: 'https://bigassmessage.com/', title: "Big Ass Message"},
    {url: 'https://www.airpano.com/', title: "AirPano"},
    {url: 'https://radio.garden/', title: "Radio Garden"},
    {url: 'https://www.window-swap.com/', title: "Window Swap"},
    {url: 'https://www.webcamtaxi.com/', title: "Webcam Taxi"},
    {url: 'https://www.virtualvacation.us/', title: "Virtual Vacation"},
    {url: 'https://www.geocaching.com/play', title: "Geocaching"},
    {url: 'https://www.noisetorch.com/', title: "NoiseTorch"},
    {url: 'https://www.rainymood.com/', title: "Rainy Mood"},
    {url: 'https://www.lofi.cafe/', title: "Lofi Cafe"},
    {url: 'https://coffitivity.com/', title: "Coffitivity"},
    {url: 'https://www.calm.com/', title: "Calm"},
    {url: 'https://www.focusatwill.com/', title: "Focus@Will"},
    {url: 'https://www.thebutton.website/', title: "The Button"},
    {url: 'https://longervideos.com/', title: "Longer Videos"},
    {url: 'https://www.sanger.dk/', title: "Sanger.dk"},
    {url: 'http://www.fallingfalling.com/', title: "Falling Falling"},
    {url: 'http://www.ferryhalim.com/orisinal/g6/circles.htm', title: "Circles"},
    {url: 'https://www.clicktorelease.com/code/css3dtest/bunny.html', title: "CSS 3D Bunny"},
    {url: 'http://www.nelson-haha.com/', title: "Nelson Haha"},
    {url: 'https://pixels.schlau.biz/', title: "Pixels"},
    {url: 'https://www.shadertoy.com/view/MdSyzW', title: "Shadertoy"},
    {url: 'https://www.addictinggames.com/funny', title: "Addicting Games"},
    {url: 'https://www.zombo.com/', title: "Zombo.com"},
    {url: 'https://neal.fun/size-of-space/', title: "Size of Space"},
    {url: 'https://neal.fun/baby-gender-predictor/', title: "Baby Gender Predictor"},
    {url: 'https://neal.fun/where-babies-come-from/', title: "Where Babies Come From"},
    {url: 'https://neal.fun/wikipedia-speedrun/', title: "Wikipedia Speedrun"},
    {url: 'https://neal.fun/money-printer/', title: "Money Printer"},
    {url: 'https://neal.fun/computers/', title: "Computers"},
    {url: 'https://neal.fun/internet-traffic/', title: "Internet Traffic"},
    {url: 'https://neal.fun/useless-websites/', title: "Useless Websites"},
    {url: 'https://neal.fun/million-dollar-homepage/', title: "Million Dollar Homepage"},
    {url: 'https://neal.fun/every-second/', title: "Every Second"},
    {url: 'https://neal.fun/popular-words/', title: "Popular Words"},
    {url: 'https://neal.fun/how-many-things/', title: "How Many Things"},
    {url: 'https://neal.fun/the-world-remade/', title: "The World Remade"},
    {url: 'https://neal.fun/universe-size/', title: "Universe Size"},
    {url: 'https://neal.fun/who-wants-to-be-a-millionaire/', title: "Who Wants to Be a Millionaire"},
    {url: 'https://pointer.toys/', title: "Pointer Toys"},
    {url: 'https://www.mapofweird.com/', title: "Map of Weird"},
    {url: 'https://make-everything-ok.com/', title: "Make Everything OK"},
    {url: 'https://thefuckingweather.com/', title: "The Fucking Weather"},
    {url: 'https://isitchristmas.com/', title: "Is It Christmas"},
    {url: 'https://random.cat/', title: "Random Cat"},
    {url: 'https://random.dog/', title: "Random Dog"},
    {url: 'https://www.awesomestufftobuy.com/', title: "Awesome Stuff to Buy"},
    {url: 'https://www.craigslist.org/about/best/sfo/', title: "Craigslist Best of"},
    {url: 'https://www.studiocromie.com/games/duckhunt/', title: "Duck Hunt"},
    {url: 'https://www.thelongestlistofthelongeststuffatthelongestdomainnameatlonglast.com/', title: "The Longest List"},
    {url: 'https://www.worldslongestjoke.com/', title: "World's Longest Joke"},
    {url: 'https://www.pleated-jeans.com/useless-websites/', title: "Pleated Jeans"},
    {url: 'https://www.randomthings.com/', title: "Random Things"},
    {url: 'https://www.drawastickman.com/', title: "Draw a Stickman"},
    {url: 'https://www.howold.net/', title: "How Old"},
    {url: 'https://www.whatismybrowser.com/', title: "What Is My Browser"},
    {url: 'https://www.findtheinvisiblecow.com/', title: "Find the Invisible Cow"},
    {url: 'https://www.instantrimshot.com/', title: "Instant Rimshot"},
    {url: 'https://www.isitdownorjustme.com/', title: "Is It Down or Just Me"},
    {url: 'https://www.thefacesoffacebook.com/', title: "The Faces of Facebook"},
    {url: 'https://www.agoodmovietowatch.com/', title: "A Good Movie to Watch"},
    {url: 'https://www.bouncyballs.org/', title: "Bouncy Balls"},
    {url: 'https://www.timeanddate.com/worldclock/full.html', title: "World Clock"},
    {url: 'https://www.google.com/earth/resources/cutout/', title: "Google Earth Cutout"},
    {url: 'https://www.clicktoflash.com/', title: "ClickToFlash"},
    {url: 'https://www.pixelthoughts.co/', title: "Pixel Thoughts"},
    {url: 'https://www.pointercrate.com/', title: "Pointercrate"},
    {url: 'https://www.trashloop.com/', title: "Trashloop"},
    {url: 'https://www.hanzismatter.com/', title: "Hanzi Matter"},
    {url: 'https://www.null.net/', title: "Nullnet"},
    {url: 'https://www.isitdownrightnow.com/', title: "Is It Down Right Now"},
    {url: 'https://www.howmanyofme.com/', title: "How Many of Me"},
    {url: 'https://www.randy.club/', title: "Randy Club"},
    {url: 'https://www.pool.toys/', title: "Pool Toys"},
    {url: 'https://www.draw.toys/flip-grid/neat-nine/3-holes/', title: "Draw Toys"},
    {url: 'https://www.thisissand.com/', title: "This Is Sand"},
    {url: 'https://www.myfonts.com/WhatTheFont/', title: "WhatTheFont"},
    {url: 'https://www.remove.bg/', title: "Remove Background"},
    {url: 'https://waifu2x.udp.jp/', title: "Waifu2x"},
    {url: 'https://www.bigassmessage.com/', title: "Big Ass Message"},
    {url: 'https://www.airpano.com/', title: "AirPano"},
    {url: 'https://www.radio.garden/', title: "Radio Garden"},
    {url: 'https://www.window-swap.com/', title: "Window Swap"},
    {url: 'https://www.webcamtaxi.com/', title: "Webcam Taxi"},
    {url: 'https://www.virtualvacation.us/', title: "Virtual Vacation"},
    {url: 'https://www.geocaching.com/play', title: "Geocaching"},
    {url: 'https://www.noisetorch.com/', title: "NoiseTorch"},
    {url: 'https://www.rainymood.com/', title: "Rainy Mood"},
    {url: 'https://www.lofi.cafe/', title: "Lofi Cafe"},
    {url: 'https://www.coffitivity.com/', title: "Coffitivity"},
    {url: 'https://www.calm.com/', title: "Calm"},
    {url: 'https://www.focusatwill.com/', title: "Focus@Will"},
    {url: 'https://www.thebutton.website/', title: "The Button"},
    {url: 'https://longervideos.com/', title: "Longer Videos"},
    {url: 'https://www.sanger.dk/', title: "Sanger.dk"},
    {url: 'http://www.fallingfalling.com/', title: "Falling Falling"},
    {url: 'http://www.ferryhalim.com/orisinal/g6/circles.htm', title: "Circles"},
    {url: 'https://www.clicktorelease.com/code/css3dtest/bunny.html', title: "CSS 3D Bunny"},
    {url: 'http://www.nelson-haha.com/', title: "Nelson Haha"},
    {url: 'https://pixels.schlau.biz/', title: "Pixels"},
    {url: 'https://www.shadertoy.com/view/MdSyzW', title: "Shadertoy"},
    {url: 'https://www.addictinggames.com/funny', title: "Addicting Games"},
    {url: 'https://www.zombo.com/', title: "Zombo.com"},
    {url: 'https://www.whatsmystarbucksname.com/', title: "What's My Starbucks Name"},
    {url: 'http://www.everydayim.com/', title: "Every Day I'm"},
    {url: 'https://www.boringboringboring.com/', title: "Boring Boring Boring"},
    {url: 'https://www.imaninja.com/', title: "I'm a Ninja"},
    {url: 'https://www.thepigeon.org/', title: "The Pigeon"},
    {url: 'http://www.isitwhite.com/', title: "Is It White"},
    {url: 'http://www.iamthewalrus.com/', title: "I Am the Walrus"}
];